version: "3.0"

services:
  db:
    image: wandersuite/wander:${TAG_VERSION}
    environment:
      - POSTGRES_DB=${DBNAME}
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_USER=${DBUSER}
    ports:
      - "5433:5432"
