version: "3.0"

services:
  db:
    image: wandersuite/db:${TAG_VERSION}
    environment:
      - POSTGRES_DB=${DBNAME}
      - POSTGRES_PASSWORD=${DBPASS}
      - POSTGRES_USER=${DBUSER}
    ports:
      - "5432:5432"
